version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-node
      - image: circleci/postgres:9.6.2-alpine
    working_directory: ~/andriypihura/mow_api
    steps:
      - checkout
      - restore_cache:
          keys:
            - mow-dependencies-{{ checksum "Gemfile.lock" }}
      - run: gem update --system
      - run: gem install bundler
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: mow-dependencies-{{ checksum "Gemfile.lock" }}
      - run: |-
          mkdir -p config && echo 'test:
            database: circle_ruby_test
            encoding: utf8
            adapter: postgresql
            pool: 5
            timeout: 5000
            username: root
            host: localhost' > config/database.yml
      - run:
          command: RAILS_ENV=test bundle exec rake db:setup
      - run:
          name: run tests
          command: bundle exec rspec --format progress
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
