default: &default
  encoding: utf8
  adapter: postgresql
  database: menuonweb
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: menuonweb_test

development:
  <<: *default

production:
  <<: *default
